Assets/Scenes/CharacterSelection.unity
Assets/Scenes/StageSelection.unity
Assets/Scenes/StageSelection.unity.meta
Assets/Script/Menu/CharacterInfo.cs
Assets/Script/Menu/CharacterInfo.cs.meta
Assets/Script/Menu/ToStage.cs
Assets/Script/Menu/ToStage.cs.meta
Assets/Script/Menu/ToStart.cs
Assets/Script/Menu/ToStart.cs.meta

캐릭터 선택, 스테이지 선택 UI부분
버튼 UI와  캐릭터 UI 부족

feat: StageSelectionUI & CharacterSelectionUI complete

---

Assets/Scenes/MainAchievements.unity
Assets/Script/Menu/CollectionItemInfo.cs
Assets/Script/Menu/UserAchi.cs

Achievements 체크박스가 인게임 내에서 변경되지 않도록 수정
Collection 일부 주석처리
UserAchi 내부 변수 이름 변경

feat: Achi 체크박스 수정, Collection 주석처리

---

Assets/Prefabs/Enemy/EnemyBat.prefab
Assets/Prefabs/Enemy/EnemyMira.prefab
Assets/Prefabs/Enemy/EnemyZombie.prefab
Assets/Prefabs/Player.prefab
Assets/Prefabs/Weapon/Circle.prefab
Assets/Script/Enemy/Enemy.cs
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/Physics2DSettings.asset
ProjectSettings/TagManager.asset

layer에 player, monster, weapon 추가
tag에 weapon 추가
몬스터 넉백 스크립트 작성

feat: 몬스터 layer 추가, 몬스터 처치 및 넉백

---

Assets/Prefabs/LevelUpUI.prefab
Assets/Prefabs/LevelUpUI.prefab.meta
Assets/Scenes/InGame.unity
Assets/Script/Player/Character.cs
Assets/Script/System/Constants.cs
Assets/Script/System/Enums.cs
Assets/Script/System/LevelUpUIManager.cs
Assets/Script/System/LevelUpUIManager.cs.meta
Assets/Script/System/PickButton.cs
Assets/Script/System/PickButton.cs.meta
Assets/Script/Weapon/Weapon.cs

랜덤 뽑기 시스템
레벨업 소지 장비 UI 및 연동
레벨업 스탯 UI 및 연동
레벨업 뽑기 UI 및 연동
레벨업 관련 UI 담은 GameObject를 prefab화하여 관리

chore: Make LevelUpUI GameObject into Prefab

---

Assets/Script/Player/Character.cs
Assets/Script/System/RandomPickUpSystem.cs
Assets/Script/System/RandomPickUpSystem.cs.meta

Character 클래스 내에 장비 뽑기 관련 함수들을 RandomPickUpSystem 클래스를 새로 작성하여 넘겨줌

refactor: Separate RandomPickUpSystem class from Character

---

Assets/Scenes/InGame.unity

chore: remove duplicated LevelUpUI GameObject

---

Assets/Prefabs/Weapon/Knife.prefab
Assets/Script/Equipment/Weapon/Knife.cs
Assets/Script/Equipment/Weapon/Knife.cs.meta
Assets/Script/Equipment/Weapon/TestWeapon.cs
Assets/Script/Equipment/Weapon/Weapon.cs

docs: modify Weapon.cs

---

Assets/Script/Enemy/EnemyScriptableObject.cs
Assets/Script/Enemy/EnemySpawner.cs
Assets/Script/Equipment/Accessory/Accessory.cs
Assets/Script/Equipment/Weapon/Weapon.cs
Assets/Script/GameData/EquipmentData.cs
Assets/Script/Menu/ChargeAccessory.cs
Assets/Script/Menu/OptionManager.cs
Assets/Script/Menu/Quit.cs
Assets/Script/Menu/SceneMove.cs
Assets/Script/Menu/StageInfo.cs
Assets/Script/Menu/UserPowerUp.cs
Assets/Script/PickUps/CoinPickup.cs
Assets/Script/PickUps/DropSpawner.cs
Assets/Script/PickUps/ExperiencePickUp.cs
Assets/Script/Player/CamController.cs
Assets/Script/Player/Character.cs
Assets/Script/Player/HealthBar.cs
Assets/Script/Player/PlayerCollector.cs
Assets/Script/Player/PlayerHp.cs
Assets/Script/Player/TestCharacterSpack.cs
Assets/Script/PoolManager.cs
Assets/Script/System/ICollectible.cs
Assets/Script/System/OptionUIManager.cs
Assets/Script/System/PickButton.cs
Assets/Script/System/RandomPickUpSystem.cs
Assets/Script/System/RepositionTile.cs
Assets/Script/System/SkillFiringSystem.cs
Assets/Script/System/WeightedRandomPicker.cs

refactor: 인코딩 UTF-8 with BOM으로 변경

---

Assets/Script/Enemy/Enemy.cs
Assets/Script/Equipment/EquipmentManagementSystem.cs
Assets/Script/GameManager.cs
Assets/Script/Menu/GameResult.cs

feat: 무기별 총 피해량, 초당 피해량 완료

---

Assets/Scenes/InGame.unity

InGameScene에 LevelupUI OptionUI Accessory Asset추가완료

chore: InGameScene에 LevelupUI OptionUI Accessory Asset추가완료

---

Assets/Scenes/InGame.unity

SkillFiringSystem에 MagicWandEvolution 추가(인덱스 1)

chore: add MagicWandEvolution to SkillFiringSystem

---

Assets/Scenes/CharacterSelection.unity
Assets/Scenes/MainscreenOption.unity
Assets/Script/Menu/CharacterInfo.cs
Assets/Script/Menu/ScreenRatio.cs
Assets/Script/Menu/ScreenRatio.cs.meta

feat: Screen ratio feature

---

Assets/Resources/MapData/Stage1.asset
Assets/Scenes/CharacterSelection.unity
Assets/Scenes/MainAchievements.unity
Assets/Scenes/MainCollection.unity
Assets/Scenes/MainScreen.unity
Assets/Scenes/MainscreenOption.unity
Assets/Scenes/PowerUp.unity
Assets/Scenes/Script/CharacterSelection/CharacterInfoOfSelectionScene.cs
Assets/Scenes/Script/StageSelection/StageOfSelectionScene.cs
Assets/Scenes/StageSelection.unity
ProjectSettings/EditorBuildSettings.asset

Hotfix yhj0329

---

Assets/Scenes/CharacterSelection.unity
Assets/Scenes/Script/CharacterSelection/CharacterInfoOfSelectionScene.cs
Assets/Scenes/Script/StageSelection/StageOfSelectionScene.cs
Assets/Scenes/StageSelection.unity

Character,Stage Scene SetMoneyText

refactor:Character,Stage Scene SetMoneyText

---

Assets/Scenes/InGame.unity
Assets/Scenes/MainscreenOption.unity
Assets/Scenes/Script/Common/GameData/EquipmentData.cs
Assets/Scenes/Script/Common/GameData/UserDataManager.cs
Assets/Scenes/Script/InGame/Equipment/Accessory/Accessory.cs
Assets/Scenes/Script/InGame/Equipment/EquipmentManagementSystem.cs

fix: refactor pianoop

---

Assets/Scenes/Script/InGame/Equipment/EquipmentManagementSystem.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Weapon.cs
Assets/Scenes/Script/InGame/GameManager.cs
Assets/Scenes/Script/InGame/Player/Character.cs

Develop apply health stat

---

Assets/Scenes/Script/Common/GameData/EquipmentData.cs
Assets/Scenes/Script/InGame/Equipment/Accessory/Accessory.cs
Assets/Scenes/Script/InGame/Equipment/EquipmentManagementSystem.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/EbonyWings.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Peachone.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Weapon.cs

무기 업그레이드(마스터 했을 때), 악세서리 업그레이드(최초 획득 시) 시에 진화 가능 여부 검사 후 진화 처리

feat: Weapon evolution in Weapon.Upgrade() and Acc.Upgrade()

---

Assets/Resources/GameData/ItemExplainDataEnglish.json
Assets/Resources/GameData/ItemExplainDataEnglish.json.meta
Assets/Resources/GameData/ItemExplainDataKorean.json
Assets/Resources/GameData/ItemExplainDataKorean.json.meta
Assets/Resources/Weapons/1Img.png.meta
Assets/Resources/Weapons/2Img.png.meta
Assets/Resources/Weapons/6Img.png.meta
Assets/Scenes/Script/MainAchievements/AchiInfo.cs
Assets/Scenes/Script/MainCollection/CollectionItemInfo.cs
Assets/Scenes/Script/PowerUp/PowerUpInfo.cs
Assets/Sprite/Enemy/bat_sprite.png.meta
Assets/Sprite/GUI/Images/frame_01.png.meta
Assets/Sprite/GUI/Images/frame_02.png.meta
Assets/Sprite/GUI/Images/frame_05.png.meta
Assets/Sprite/GUI/Images/gauge_01.png.meta
Assets/Sprite/GUI/Images/gauge_02.png.meta
Assets/Sprite/GUI/Images/slot_frame.png.meta
Assets/Sprite/MapTile/Stage1/TX Tileset Grass.png.meta

json파일을 통해 Collection,Achi,PowerUp코드 간결화

refactor: json파일을 통해 Collection,Achi,PowerUp코드 간결화

---

Assets/Scenes/Script/InGame/Player/Character.cs

feat:Character Armor 구현

---

Assets/Scenes/PowerUp.unity
Assets/Scenes/Script/PowerUp/ChargePowerUp.cs
Assets/Scenes/Script/PowerUp/PowerUpInfo.cs

PowerUp Scene에서 모두강화한 후 활성화 비활성화 구현 완료

Develop power up active toggle

---

Assets/Prefabs/Weapon/EbonyWings.prefab
Assets/Prefabs/Weapon/EvoPeachone.prefab
Assets/Prefabs/Weapon/Peachone.prefab
Assets/Scenes/Script/InGame/Equipment/EquipmentManagementSystem.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/EbonyWings.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/EvoPeachBoundery.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Peachone.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Weapon.cs

비둘기 쌍 무기 기본 상태가 진화로 취급되던 오류 해결

Hotfix peachone and ebony wings

---

Assets/Prefabs/Weapon/0.prefab
Assets/Prefabs/Weapon/0.prefab.meta
Assets/Prefabs/Weapon/3.prefab
Assets/Prefabs/Weapon/3.prefab.meta
Assets/Prefabs/Weapon/4.prefab
Assets/Prefabs/Weapon/4.prefab.meta
Assets/Prefabs/Weapon/5.prefab
Assets/Prefabs/Weapon/5.prefab.meta
Assets/Prefabs/Weapon/9.prefab
Assets/Prefabs/Weapon/9.prefab.meta
Assets/Scenes/InGame.unity

Connect temp prefab to SkillFiringSystem's Weapon Prefabs

chore: connect temp prefab to SkillFiringSystem's Weapon Prefabs

---

Assets/Prefabs/Weapon/EvoGralic.prefab
Assets/Prefabs/Weapon/EvoGralic.prefab.meta
Assets/Scenes/InGame.unity
Assets/Scenes/Script/InGame/Common/GameManager.cs
Assets/Scenes/Script/InGame/Enemy/Enemy.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/SkillFiringSystem.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Weapon.cs

Gralic 진화형 Prefab 구현, 피흡과 공격력 증가, 크기 증가완료, 마늘 넉백 거리 증가 구현

Develop evo gralic

---

Assets/Prefabs/InGameUI/OptionUI.prefab
Assets/Scenes/GameResultScene.unity
Assets/Scenes/Script/Common/GameData/UserDataManager.cs
Assets/Scenes/Script/Common/GameData/UserInfo.cs
Assets/Scenes/Script/GameResultScene/GameResult.cs
Assets/Scenes/Script/InGame/Common/GameManager.cs
Assets/Scenes/Script/InGame/Common/QuitInGame.cs
Assets/Scenes/Script/InGame/Common/QuitInGame.cs.meta
Assets/Scenes/Script/PowerUp/ChargePowerUp.cs

InGame종료시 GameManager 제거 및 재생성 버그 수정
게임 데이터 kill, gold, time UserData에 저장

fix:InGame종료시 GameManager 제거 및 재생성 버그 수정

---

Assets/Scenes/Script/InGame/Common/GameManager.cs
Assets/Scenes/Script/InGame/UI/OptionUIManager.cs

InGame에서 OptionUI를 ESC키를 누르면 OFF되는 기능 추가

feat:InGame에서 OptionUI를 ESC키를 누르면 ON/OFF되는 기능 추가 원래 ON만 됐었음

---

Assets/Prefabs/Weapon/0.prefab
Assets/Prefabs/Weapon/3.prefab
Assets/Prefabs/Weapon/4.prefab
Assets/Prefabs/Weapon/5.prefab
Assets/Prefabs/Weapon/9.prefab
Assets/Prefabs/Weapon/EbonyWings.prefab
Assets/Prefabs/Weapon/EvoGralic.prefab
Assets/Prefabs/Weapon/EvoPeachone.prefab
Assets/Prefabs/Weapon/Gralic.prefab
Assets/Prefabs/Weapon/Knife.prefab
Assets/Prefabs/Weapon/KnifeEvolution.prefab
Assets/Prefabs/Weapon/MagicWand.prefab
Assets/Prefabs/Weapon/MagicWandEvolution Variant.prefab
Assets/Prefabs/Weapon/Peachone.prefab
Assets/Scenes/Script/Common/GameData/Constants.cs
Assets/Scenes/Script/InGame/Equipment/EquipmentManagementSystem.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/EbonyWings.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Gralic.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Knife.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/MagicWand.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Peachone.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/SkillFiringSystem.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Weapon.cs

weapon class를 각각 무기 class에 상속시켰음.

chore: weapon class abstraction

---

Assets/Scenes/Script/Achievements/AchiInfo.cs
Assets/Scenes/Script/Achievements/UserAchi.cs
Assets/Scenes/Script/Collection/CollectionItemInfo.cs
Assets/Scenes/Script/Collection/UserCollection.cs
Assets/Scenes/Script/InGame/Equipment/EquipmentManagementSystem.cs
Assets/Scenes/Script/InGame/RandomPickUpSystem.cs
Assets/Scenes/Script/Option/OptionManager.cs

refactor: all scene script naming

---

Assets/Prefabs/InGameUI/GameOverUI.prefab
Assets/Prefabs/InGameUI/GameOverUI.prefab.meta
Assets/Prefabs/InGameUI/InGameUI.prefab
Assets/Prefabs/InGameUI/LevelUpUI.prefab
Assets/Prefabs/InGameUI/OptionUI.prefab
Assets/Scenes/InGame.unity

fix: Multiple canvases have been merged into one canvas in Ingame scene

---

Assets/Scenes/InGame.unity

이전 Ingame scene의 canvas를 하나로 합치는 과정에서 사망 후 나와야 하는 GameOver창의 크기가 0으로 바뀌었던 것을 수정

fix: GameOverUI scale

---

Assets/Scenes/Script/Option/OptionManager.cs
Packages/manifest.json
Packages/packages-lock.json
ProjectSettings/BurstAotSettings_StandaloneWindows.json
ProjectSettings/CommonBurstAotSettings.json
ProjectSettings/ProjectSettings.asset
ProjectSettings/QualitySettings.asset
ProjectSettings/TimelineSettings.asset
README.md

빌드관련 코드 및 설정 수정
Option에서 외부 저장 파일(.json) 불러오는 기능 주석처리

Release build

---

Assets/Prefabs/PickUps/CoinGold.prefab
Assets/Prefabs/PickUps/HeartRed.prefab
Assets/Prefabs/PickUps/expBlue1.5.prefab
Assets/Prefabs/PickUps/expBlue1.prefab
Assets/Prefabs/PickUps/expBlue2.5.prefab
Assets/Prefabs/PickUps/expBlue2.prefab
Assets/Prefabs/PickUps/expBlue3.prefab
Assets/Prefabs/PickUps/expRed30.prefab
Assets/Prefabs/Stage1/chest.prefab
Assets/Scenes/Script/InGame/Map/Object/GoToPlayer.cs
Assets/Scenes/Script/InGame/Map/Object/TresureChestPickup.cs
ProjectSettings/TagManager.asset

Develop connect treasure chest

---

Assets/Scenes/Script/Main/MainMenuManager.cs

Main scene에서 선택지 확인으로 할당된 키를 keypadEnter에서 엔터키(return)로 변경

fix: keypadEnter key code to return key

---

Assets/Scenes/InGame.unity

fix: player graviry scale 0

---

Assets/Scenes/Script/InGame/Common/GameManager.cs

fix: 쓸모없는 코드 삭제

---

Assets/Scenes/Achievements.unity
Assets/Scenes/CharacterSelection.unity
Assets/Scenes/Collection.unity
Assets/Scenes/GameResult.unity
Assets/Scenes/InGame.unity
Assets/Scenes/Loading.unity
Assets/Scenes/Main.unity
Assets/Scenes/Option.unity
Assets/Scenes/PowerUp.unity
Assets/Scenes/Script/InGame/Common/GameManager.cs
Assets/Scenes/Script/Option/OptionManager.cs
Assets/Scenes/StageSelection.unity

Canvas Scaler를 Constant pixel size에서 scale with screensize로 변경

fix: canvas scaler

---

Assets/Scenes/Achievements.unity
Assets/Scenes/CharacterSelection.unity
Assets/Scenes/Collection.unity
Assets/Scenes/GameResult.unity
Assets/Scenes/InGame.unity
Assets/Scenes/Loading.unity
Assets/Scenes/Main.unity
Assets/Scenes/Option.unity
Assets/Scenes/PowerUp.unity
Assets/Scenes/Script/Option/OptionalController.cs
Assets/Scenes/StageSelection.unity

창 모드 스크린 사이즈가 1920 1080 적용되지 않던 버그 수정

fix: screen size(1920x1080)

---

Assets/Scenes/Loading.unity
Assets/Scenes/Script/StageSelection/StageOfSelectionScene.cs
Assets/Scenes/StageSelection.unity

fix: Fixed map selection mis-matching bug

---

Assets/Resources/GameData/PowerUpDataKorean.json
Assets/Resources/GameData/PowerUpDataKorean.json.meta
Assets/Scenes/Script/PowerUp/PowerUpInfo.cs

PowerUpData json file naming 변경

fix: PowerUpData json file name

---

Assets/Scenes/Script/InGame/UI/TreasureChest.cs

보물상자 1, 3, 5개 드랍 확률을 greed에서 luck으로 변경

fix: greed to luck

---

Assets/Scenes/Script/InGame/Equipment/Weapon/EbonyWings.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/EvoPeachBoundery.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/PeachBoundery.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Peachone.cs

비둘기 무기들에 Amount 스탯 적용되지 않고 있던 버그 수정

feat: apply amount stat

---

Assets/Scenes/Option.unity
Assets/Scenes/Script/Common/GameData/UserInfo.cs
Assets/Scenes/Script/Option/OptionManager.cs

feat: default data setting and cheat data setting button in Option scene

---

Assets/Scenes/Script/Common/GameData/EquipmentData.cs
Assets/Scenes/Script/InGame/Equipment/EvoWeaponTest.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/EbonyWings.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Peachone.cs
Assets/Scenes/Script/InGame/Equipment/Weapon/Weapon.cs

Develop checking evo weapon
